spring.profiles.active=application-gateway
spring.application.name=ApiGateway
spring.cloud.config.uri=http://localhost:8888

services.bff-id=bff-service
services.bff-url=http://localhost
services.bff-port=8081
services.bff-pattern=/api/site-bff/**